# Generated by Django 5.0.3 on 2024-04-30 20:39

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(default=0, unique=True, validators=[profiles.models.is_valid_year]),
        ),
    ]
