# Generated by Django 5.0.3 on 2024-03-28 17:03

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_group_options_alter_year_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(unique=True, validators=[profiles.models.is_valid_year]),
        ),
    ]
