# Generated by Django 5.0.3 on 2024-04-30 21:15

import django.db.models.deletion
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_year_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.IntegerField(default=0, null=True, validators=[profiles.models.is_valid_group]),
        ),
        migrations.AlterField(
            model_name='group',
            name='year',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='profiles.year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.year'),
        ),
    ]
