# Generated by Django 5.0.3 on 2024-03-28 17:05

import django.db.models.deletion
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_year_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='profiles.year', validators=[profiles.models.is_valid_group]),
        ),
    ]
