# Generated by Django 5.0.3 on 2024-04-30 21:45

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_group_number_alter_group_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.IntegerField(default=0, validators=[profiles.models.is_valid_group]),
        ),
    ]
