# Generated by Django 5.0.3 on 2024-04-24 09:17

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_group_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(null=True, unique=True, validators=[profiles.models.is_valid_year]),
        ),
    ]
