# Generated by Django 5.0.3 on 2024-04-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_year_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
