# Generated by Django 5.0.3 on 2024-05-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_student_group_alter_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(choices=[('PROFESSEUR', 'Professeur'), ('MAITRE ASSISTANT A', 'Maître assistant A'), ('MAITRE ASSISTANT B', 'Maître assistant B')], max_length=255, null=True),
        ),
    ]
