# Generated by Django 5.0.3 on 2024-05-01 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_teacher_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_editor_teacher',
        ),
    ]
