# Generated by Django 5.0.3 on 2024-05-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_user_is_editor_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
