# Generated by Django 5.0.3 on 2024-03-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_student_teacher_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('STAFF', 'Staff'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='STUDENT', max_length=255),
        ),
    ]
