# Generated by Django 5.0.3 on 2024-03-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_delete_student_delete_teacher_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_editor_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
