# Generated by Django 5.0.3 on 2024-04-30 20:36

import django.db.models.deletion
import ressources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
                ('coefficient', models.IntegerField(validators=[ressources.models.valid_coeff])),
                ('main_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.teacher')),
                ('teachers', models.ManyToManyField(related_name='subjects', to='profiles.teacher')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.year')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.FileField(upload_to='courses/')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.subject')),
            ],
        ),
    ]
