# Generated by Django 5.0.3 on 2024-03-28 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_group_options_alter_year_options'),
        ('ressources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.year'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.teacher'),
        ),
    ]
