# Generated by Django 5.0.3 on 2024-05-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
