# Generated by Django 5.0.3 on 2024-06-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0002_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='default/girlImg.svg', upload_to='news/images/'),
        ),
    ]
