# Generated by Django 5.0.3 on 2024-05-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_group_year'),
        ('ressources', '0002_alter_subject_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(related_name='subjects', to='profiles.teacher'),
        ),
    ]
