# Generated by Django 5.0.3 on 2024-05-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0002_td'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='td',
            options={'verbose_name': 'TD', 'verbose_name_plural': 'TDs'},
        ),
    ]
