# Generated by Django 5.0.3 on 2024-03-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0002_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='coefficient',
            field=models.IntegerField(null=True),
        ),
    ]
