# Generated by Django 5.0.3 on 2024-03-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0003_subject_coefficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='coefficient',
            field=models.IntegerField(),
        ),
    ]
