# Generated by Django 5.0.3 on 2024-05-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0003_alter_course_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='td',
            name='number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='tp',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
