# Generated by Django 5.0.3 on 2024-05-05 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('ressources', '0003_alter_td_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.teacher'), related_name='subjects', to='profiles.teacher'),
        ),
    ]
