# Generated by Django 5.0.3 on 2024-05-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0004_remove_course_subject_alter_subject_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='number',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
