# Generated by Django 5.0.3 on 2024-03-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0004_alter_subject_coefficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
