# Generated by Django 5.0.3 on 2024-05-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0005_chapter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
