# Generated by Django 5.0.3 on 2024-05-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0006_alter_chapter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='place',
            field=models.CharField(default='Amphi D'),
        ),
    ]
