# Generated by Django 5.0.3 on 2024-05-13 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0006_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachement',
            field=models.FileField(blank=True, null=True, upload_to='forum/'),
        ),
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ressources.post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ressources.post')),
            ],
            bases=('ressources.post',),
        ),
    ]
