# Generated by Django 5.0.3 on 2024-05-13 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0007_post_attachement_post_upvotes_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ressources.subject'),
        ),
    ]
