# Generated by Django 5.0.3 on 2024-05-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0007_chapter_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='place',
        ),
        migrations.AddField(
            model_name='subject',
            name='place',
            field=models.CharField(default='Amphi D'),
        ),
    ]
