# Generated by Django 5.0.3 on 2024-05-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0008_alter_forum_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
