# Generated by Django 5.0.3 on 2024-05-06 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0009_alter_subject_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.FileField(upload_to='tps/')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.chapter')),
            ],
            options={
                'verbose_name': 'TP',
                'verbose_name_plural': 'TPs',
            },
        ),
    ]
