# Generated by Django 5.0.3 on 2024-05-13 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0009_alter_post_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
