# Generated by Django 5.0.3 on 2024-05-09 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('ressources', '0010_tp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.subject')),
            ],
        ),
    ]
