# Generated by Django 5.0.3 on 2024-05-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0012_homework'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name_plural': 'Homework'},
        ),
        migrations.AlterField(
            model_name='homework',
            name='content',
            field=models.FileField(upload_to='devoirs/'),
        ),
    ]
