# Generated by Django 5.0.3 on 2024-05-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0013_alter_comment_forum_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
