# Generated by Django 5.0.3 on 2024-05-10 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0014_question_homework_deadline_answer_quiz_question_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
    ]
