# Generated by Django 5.0.3 on 2024-05-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0015_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
