# Generated by Django 5.0.3 on 2024-05-15 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('ressources', '0020_comment_downvotes_post_downvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.year'),
        ),
    ]
