# Generated by Django 5.0.3 on 2024-05-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0021_news_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='attachement',
            new_name='attachment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='attachement',
            new_name='attachment',
        ),
        migrations.RemoveField(
            model_name='news',
            name='attachement',
        ),
        migrations.AddField(
            model_name='news',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='news/attachments/'),
        ),
    ]
